#!/bin/sh

# Run this script to receive (via RabbitMQ) notifications from vmcatcher
# and register respective images to ~okeanos via kamaki CLI

HERE="`dirname $0`"
LOG=${HERE}/snf-vmcatcher.log

nohup java -jar ${HERE}/snf-vmcatcher.jar \
  -v \
  -conf ${HERE}/application.conf \
  dequeue \
  -server \
  -handler gr.grnet.egi.vmcatcher.handler.VMRegistrationHandler \
  "$@" >> $LOG &

