/*
 * Copyright (C) 2014 GRNET S.A.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package gr.grnet.egi.vmcatcher.message

/**
 *
 * @author Christos KK Loverdos <loverdos@gmail.com>
 */
sealed trait Message

// JSON as it is generated by the vmcatcher (python) script
case class VmCatcherScriptJSON(json: String) extends Message

// JSON describing an image as it appears in an image list
case class ImageJSON(imageConfig: ImageConfig) extends Message

case class UnparsedMessage(error: String) extends Message

/**
 *
 * @author Christos KK Loverdos <loverdos@gmail.com>
 */
object Message {
  def parseJson(json: String): Message = {
    try {
      val imageConfig = ImageConfig.ofString(json)
      val isImageJSON = imageConfig.hasDcIdentifier && imageConfig.hasHvURI
      if(isImageJSON) {
        ImageJSON(imageConfig)
      } else {
        VmCatcherScriptJSON(json)
      }
    }
    catch {
      case e: Exception ⇒
        UnparsedMessage(e.toString)
    }
  }
}
